python -m infer \
    --seed=0 \
    --data_name=Xenium_mouse \
    --analysis=GAN --task=$TASK \
    --gene_num=379 \
    --input_nc=1 \
    --n_eval=16 --n_iter=$N_ITER \
    --cell_label=kmeans_11_clusters \
    --data_path=Data/Xenium_mouse/GAN \
    --ckpt_path=Data/Xenium_mouse/GAN/dapi_True_0.5_slide_ID_numeric_3_512_crop_11_all/checkpoint \
    --save_path=Experiment_inf/Xenium_mouse/